### ISSUE TITLE
bugster-pr-create.yml Bug Report

### ISSUE THREAD

**Issue by vaibhavgoelbvu** [vaibhavgoelbvu/docs#10]
Here are the potential bugs and issues in the code:

1. The `BUGSTER_API_KEY` and `OPENAI_API_KEY` secrets are used in the `env` section of the `Bugster` step, but they are not passed as arguments to the `docker` command. This means that the container running the `bugster-pr-workflow` image will not have access to these secrets.

To fix this issue, you should pass these secrets as arguments to the `docker` command using the `env` key. Here's an example:
```yaml
- name: Bugster
  uses: docker://ghcr.io/bugster-ai/bugster-pr-workflow:latest
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    base_branch: ${{ github.event.repository.default_branch }}
    model: gpt-4
    context_limit: 8192
    min_tokens: 1000
    max_tokens: 2000
    num_reasks: 2
    BUGSTER_API_KEY: ${{ secrets.BUGSTER_API_KEY }}
    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
```
2. The `Install jq` step installs `jq` using `apt-get`, but it does not clean up the installation afterwards. This can lead to unnecessary package bloat in the container running the workflow.

To fix this issue, you should add a `clean` step after installing `jq` to remove the package. Here's an example:
```yaml
- name: Install jq
  run: |
    sudo apt-get update
    sudo apt-get install -y jq
    sudo apt-get clean
```
3. The commented-out `Check if label was added by a collaborator` step contains a syntax error. The `env` section is indented one level too far, which will cause the step to fail.

To fix this issue, you should uncomment the step and indent the `env` section correctly. Here's an example:
```yaml
- name: Check if label was added by a collaborator
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run: |
    is_collaborator=$(curl -s -H "Authorization: token $GITHUB_TOKEN " -H "Accept: application/vnd.github+json" \
      "https://api.github.com/repos/${{ github.repository }}/collaborators/${{ github.event.sender.login }}" | jq -r '.message')

    if [ "$is_collaborator" == "Not Found" ]; then
      echo "Label not added by a collaborator. Skipping action."
      exit 78
    fi
